env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:@docusaurus/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
settings:
  react:
    version: "detect"
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
